# Generated by Django 4.2.1 on 2023-05-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="details",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="link",
            field=models.URLField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="project_content",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
