# Generated by Django 4.2.1 on 2023-05-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_technology_alter_project_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
